stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    #params:
    #- data_ingestion.test_size
    outs:
    - data/raw
  preprocessing:
    cmd: python src/preprocessing.py
    deps:
    - data/raw
    - src/preprocessing.py
    outs:
    - data/interim
  feature_eng:
    cmd: python src/feature_eng.py
    deps:
    - data/interim
    - src/feature_eng.py
    #params:
    #- feature_eng.max_features
    outs:
    - data/processed
  model_training:
    cmd: python src/model_training.py
    deps:
    - data/processed
    - src/model_training.py
    #params:
    #- model_training.n_estimators
    #- model_training.random_state
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - models/model.pkl
    - src/evaluate.py
    metrics:
    - reports/metrics.json